#!/bin/bash

# Big Data Analytics Using Splunk
# By Peter Zadrozny and Raghu Kodali
# Apress, May 2013 ISBN 978-1-4302-5761-5
# Copyright (C) 2013 Peter Zadrozny and Raghu Kodali

# Chapter 9
# Load all the data into Splunk

splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2012_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2012_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2012_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2012_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2012_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2012_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2012_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2012_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2012_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2011_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2011_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2011_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2011_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2011_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2011_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2011_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2011_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2011_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2011_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2011_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2011_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2010_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2010_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2010_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2010_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2010_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2010_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2010_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2010_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2010_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2010_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2010_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2010_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2009_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2009_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2009_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2009_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2009_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2009_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2009_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2009_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2009_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2009_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2009_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2009_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2008_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2008_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2008_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2008_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2008_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2008_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2008_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2008_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2008_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2008_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2008_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2008_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2007_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2007_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2007_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2007_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2007_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2007_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2007_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2007_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2007_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2007_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2007_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2007_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2006_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2006_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2006_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2006_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2006_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2006_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2006_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2006_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2006_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2006_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2006_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2006_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2005_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2005_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2005_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2005_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2005_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2005_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2005_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2005_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2005_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2005_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2005_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2005_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2004_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2004_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2004_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2004_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2004_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2004_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2004_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2004_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2004_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2004_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2004_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2004_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2003_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2003_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2003_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2003_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2003_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2003_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2003_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2003_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2003_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2003_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2003_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2003_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2002_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2002_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2002_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2002_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2002_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2002_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2002_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2002_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2002_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2002_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2002_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2002_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2001_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2001_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2001_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2001_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2001_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2001_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2001_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2001_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2001_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2001_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2001_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2001_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2000_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2000_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2000_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2000_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2000_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2000_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2000_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2000_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2000_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2000_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2000_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_2000_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1999_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1999_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1999_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1999_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1999_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1999_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1999_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1999_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1999_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1999_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1999_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1999_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1998_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1998_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1998_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1998_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1998_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1998_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1998_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1998_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1998_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1998_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1998_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1998_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1997_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1997_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1997_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1997_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1997_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1997_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1997_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1997_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1997_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1997_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1997_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1997_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1996_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1996_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1996_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1996_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1996_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1996_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1996_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1996_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1996_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1996_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1996_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1996_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1995_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1995_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1995_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1995_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1995_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1995_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1995_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1995_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1995_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1995_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1995_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1995_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1994_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1994_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1994_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1994_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1994_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1994_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1994_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1994_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1994_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1994_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1994_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1994_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1993_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1993_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1993_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1993_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1993_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1993_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1993_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1993_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1993_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1993_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1993_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1993_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1992_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1992_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1992_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1992_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1992_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1992_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1992_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1992_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1992_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1992_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1992_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1992_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1991_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1991_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1991_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1991_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1991_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1991_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1991_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1991_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1991_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1991_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1991_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1991_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1990_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1990_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1990_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1990_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1990_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1990_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1990_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1990_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1990_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1990_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1990_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1990_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1989_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1989_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1989_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1989_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1989_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1989_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1989_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1989_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1989_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1989_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1989_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1989_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1988_9.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1988_8.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1988_7.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1988_6.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1988_5.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1988_4.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1988_3.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1988_2.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1988_1.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1988_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1988_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1988_10.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1987_12.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1987_11.csv -sourcetype FD_Source2 -host BigDBook
splunk/bin/splunk add oneshot /mnt/flight_data/On_Time_On_Time_Performance_1987_10.csv -sourcetype FD_Source2 -host BigDBook
